[workspace]
resolver = "3"
members = [
    "crates/sllm-core",
    "crates/sllm-hip-sys",
    "crates/sllm-hip",
    "crates/sllm-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
license = "MIT"

[workspace.dependencies]
sllm-core = { path = "crates/sllm-core" }
sllm-hip = { path = "crates/sllm-hip" }
sllm-hip-sys = { path = "crates/sllm-hip-sys" }
