// @generated by bindgen 0.71.1; checked in for reproducible normal builds.
// source: include/sllm/hip.h
// abi_version: 1
// options: --allowlist-type '^sllm_.*' --allowlist-function '^sllm_.*' --allowlist-var '^SLLM_.*' --no-layout-tests

use core::ffi::c_char;

pub type sllm_status_t = u32;

pub const SLLM_HIP_ABI_VERSION: u32 = 1;
pub const SLLM_HIP_LIBRARY_VERSION_MAJOR: u32 = 0;
pub const SLLM_HIP_LIBRARY_VERSION_MINOR: u32 = 1;
pub const SLLM_HIP_LIBRARY_VERSION_PATCH: u32 = 0;

pub const SLLM_STATUS_OK: sllm_status_t = 0;
pub const SLLM_STATUS_INVALID_ARGUMENT: sllm_status_t = 1;
pub const SLLM_STATUS_BUFFER_TOO_SMALL: sllm_status_t = 2;
pub const SLLM_STATUS_UNSUPPORTED: sllm_status_t = 3;
pub const SLLM_STATUS_HIP_UNAVAILABLE: sllm_status_t = 4;
pub const SLLM_STATUS_INVALID_ABI_VERSION: sllm_status_t = 5;
pub const SLLM_STATUS_RESERVED_NONZERO: sllm_status_t = 6;
pub const SLLM_STATUS_INTERNAL_ERROR: sllm_status_t = 7;
pub const SLLM_STATUS_PUBLIC_PENDING: sllm_status_t = 0x100;
pub const SLLM_STATUS_PUBLIC_TIMEOUT: sllm_status_t = 0x101;
pub const SLLM_STATUS_PUBLIC_INVALID_HANDLE: sllm_status_t = 0x102;
pub const SLLM_STATUS_PUBLIC_DEVICE_MISMATCH: sllm_status_t = 0x103;
pub const SLLM_STATUS_PUBLIC_HIP_RUNTIME_ERROR: sllm_status_t = 0x104;
pub const SLLM_STATUS_PUBLIC_BUSY: sllm_status_t = 0x105;
pub const SLLM_STATUS_PUBLIC_NOT_READY: sllm_status_t = 0x106;
pub const SLLM_STATUS_INVALID_RMSNORM_DESCRIPTOR: sllm_status_t = 0x107;
pub const SLLM_STATUS_INVALID_TENSOR_BINDING: sllm_status_t = 0x108;
pub const SLLM_STATUS_ZERO_EXTENT: sllm_status_t = 0x109;
pub const SLLM_STATUS_SHAPE_MISMATCH: sllm_status_t = 0x10a;
pub const SLLM_STATUS_STRIDE_MISMATCH: sllm_status_t = 0x10b;
pub const SLLM_STATUS_METADATA_OVERFLOW: sllm_status_t = 0x10c;
pub const SLLM_STATUS_BUFFER_OUT_OF_BOUNDS: sllm_status_t = 0x10d;
pub const SLLM_STATUS_MISALIGNED_OFFSET: sllm_status_t = 0x10e;
pub const SLLM_STATUS_UNSUPPORTED_DTYPE: sllm_status_t = 0x10f;
pub const SLLM_STATUS_UNSUPPORTED_ENCODING: sllm_status_t = 0x110;
pub const SLLM_STATUS_INVALID_EPSILON: sllm_status_t = 0x111;
pub const SLLM_STATUS_UNSUPPORTED_SCALE_MODE: sllm_status_t = 0x112;
pub const SLLM_STATUS_ALIAS_OVERLAP: sllm_status_t = 0x113;
pub const SLLM_STATUS_CONTEXT_OR_DEVICE_MISMATCH: sllm_status_t = 0x114;
pub const SLLM_STATUS_INVALID_ELEMENTWISE_DESCRIPTOR: sllm_status_t = 0x115;
pub const SLLM_STATUS_INVALID_EMBEDDING_DESCRIPTOR: sllm_status_t = 0x116;
pub const SLLM_STATUS_TOKEN_ID_OUT_OF_RANGE: sllm_status_t = 0x117;
pub const SLLM_STATUS_INVALID_MATMUL_DESCRIPTOR: sllm_status_t = 0x118;
pub const SLLM_STATUS_INVALID_ATTENTION_PREPROCESS_DESCRIPTOR: sllm_status_t = 0x119;
pub const SLLM_STATUS_POSITION_PAYLOAD_MISMATCH: sllm_status_t = 0x11a;
pub const SLLM_STATUS_INVALID_KV_STATE_DESCRIPTOR: sllm_status_t = 0x11b;
pub const SLLM_STATUS_INVALID_KV_APPEND_DESCRIPTOR: sllm_status_t = 0x11c;
pub const SLLM_STATUS_KV_LENGTH_MISMATCH: sllm_status_t = 0x11d;
pub const SLLM_STATUS_KV_CAPACITY_EXCEEDED: sllm_status_t = 0x11e;
pub const SLLM_STATUS_INVALID_CAUSAL_ATTENTION_DESCRIPTOR: sllm_status_t = 0x11f;
pub const SLLM_STATUS_CAUSAL_ATTENTION_LENGTH_MISMATCH: sllm_status_t = 0x120;
pub const SLLM_STATUS_CAUSAL_ATTENTION_STATE_BUSY: sllm_status_t = 0x121;
pub const SLLM_STATUS_INVALID_LINEAR_ATTENTION_STATE_DESCRIPTOR: sllm_status_t = 0x122;
pub const SLLM_STATUS_INVALID_LINEAR_ATTENTION_DESCRIPTOR: sllm_status_t = 0x123;
pub const SLLM_STATUS_LINEAR_ATTENTION_LENGTH_MISMATCH: sllm_status_t = 0x124;
pub const SLLM_STATUS_LINEAR_ATTENTION_STATE_BUSY: sllm_status_t = 0x125;
pub const SLLM_STATUS_INVALID_ARGMAX_DESCRIPTOR: sllm_status_t = 0x126;
pub const SLLM_STATUS_INVALID_ROTARY_DESCRIPTOR: sllm_status_t = 0x127;
pub const SLLM_STATUS_INVALID_WINDOWED_ATTENTION_DESCRIPTOR: sllm_status_t = 0x128;

pub const SLLM_HIP_RMSNORM_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_RMSNORM_KERNEL_ID_BASELINE_WAVE32_V1: u32 = 1;
pub const SLLM_HIP_RMSNORM_KERNEL_ID_BASELINE_WAVE64_V1: u32 = 2;
pub const SLLM_HIP_RMSNORM_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_RMSNORM_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_RMSNORM_MAX_N: u64 = 4096;
pub const SLLM_HIP_RMSNORM_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_RMSNORM_MAX_ROWS: u64 = 4_294_967_295;
pub const SLLM_HIP_ELEMENTWISE_VERSION: u32 = 1;
pub const SLLM_HIP_ELEMENTWISE_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_ELEMENTWISE_KERNEL_ID_COPY_V1: u32 = 1;
pub const SLLM_HIP_ELEMENTWISE_KERNEL_ID_ADD_V1: u32 = 2;
pub const SLLM_HIP_ELEMENTWISE_KERNEL_ID_SILU_MUL_V1: u32 = 3;
pub const SLLM_HIP_ELEMENTWISE_KERNEL_ID_SIGMOID_MUL_V1: u32 = 4;
pub const SLLM_HIP_ELEMENTWISE_KERNEL_ID_SCALAR_MUL_V1: u32 = 5;
pub const SLLM_HIP_ELEMENTWISE_KERNEL_ID_GELU_TANH_MUL_V1: u32 = 6;
pub const SLLM_HIP_ELEMENTWISE_KERNEL_ID_TANH_SOFTCAP_V1: u32 = 7;
pub const SLLM_HIP_ELEMENTWISE_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_ELEMENTWISE_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_ELEMENTWISE_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_ELEMENTWISE_MAX_ELEMENTS: u64 = 4_294_967_295;
pub const SLLM_HIP_EMBEDDING_VERSION: u32 = 1;
pub const SLLM_HIP_EMBEDDING_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_EMBEDDING_KERNEL_ID_GATHER_V1: u32 = 1;
pub const SLLM_HIP_EMBEDDING_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_EMBEDDING_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_EMBEDDING_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_EMBEDDING_MAX_VOCAB: u64 = 1_048_576;
pub const SLLM_HIP_EMBEDDING_MAX_HIDDEN: u64 = 4096;
pub const SLLM_HIP_EMBEDDING_MAX_TOKENS: u64 = 65_536;
pub const SLLM_HIP_MATMUL_VERSION: u32 = 1;
pub const SLLM_HIP_MATMUL_FP8_VERSION: u32 = 2;
pub const SLLM_HIP_MATMUL_NVFP4_VERSION: u32 = 3;
pub const SLLM_HIP_MATMUL_NVFP4_W4A4_VERSION: u32 = 4;
pub const SLLM_HIP_MATMUL_MXFP4_W4A4_VERSION: u32 = 5;
pub const SLLM_HIP_MATMUL_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_MATMUL_KERNEL_ID_BASELINE_BF16_FP32_V1: u32 = 1;
pub const SLLM_HIP_MATMUL_KERNEL_ID_TILED16_BF16_FP32_V2: u32 = 2;
pub const SLLM_HIP_MATMUL_KERNEL_ID_DECODE_BF16_FP32_V2: u32 = 3;
pub const SLLM_HIP_MATMUL_KERNEL_ID_HIPBLAS_DECODE_V1: u32 = 4;
pub const SLLM_HIP_MATMUL_KERNEL_ID_HIPBLAS_BF16_FP32_V2: u32 = 4;
pub const SLLM_HIP_MATMUL_KERNEL_ID_HIPBLASLT_FP8_OUTER_V1: u32 = 5;
pub const SLLM_HIP_MATMUL_KERNEL_ID_FP8_BYTE_EMULATION_V1: u32 = 6;
pub const SLLM_HIP_MATMUL_KERNEL_ID_DECODE_WAVE64_BF16_FP32_V1: u32 = 7;
pub const SLLM_HIP_MATMUL_KERNEL_ID_NVFP4_PACKED_DEQUANT_V1: u32 = 8;
pub const SLLM_HIP_MATMUL_KERNEL_ID_NVFP4_W4A4_PACKED_V1: u32 = 11;
pub const SLLM_HIP_MATMUL_KERNEL_ID_MXFP4_W4A4_DECODE_V1: u32 = 14;
pub const SLLM_HIP_MATMUL_KERNEL_ID_MXFP4_W4A4_PREFILL_V1: u32 = 15;
pub const SLLM_HIP_MATMUL_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_MATMUL_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_MATMUL_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_MATMUL_MAX_M: u64 = 65_536;
pub const SLLM_HIP_MATMUL_MAX_K: u64 = 16_384;
pub const SLLM_HIP_MATMUL_MAX_N: u64 = 262_144;
pub const SLLM_HIP_MATMUL_MAX_OUTPUT_ELEMENTS: u64 = 4_294_967_295;
pub const SLLM_HIP_ARGMAX_VERSION: u32 = 1;
pub const SLLM_HIP_ARGMAX_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_ARGMAX_KERNEL_ID_BASELINE_BF16_V1: u32 = 1;
pub const SLLM_HIP_ARGMAX_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_ARGMAX_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_ARGMAX_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_ARGMAX_MAX_V: u64 = 1_048_576;
pub const SLLM_HIP_ARGMAX_MAX_M: u64 = 4_294_967_295;
pub const SLLM_HIP_MOE_ROUTE_VERSION: u32 = 1;
pub const SLLM_HIP_MOE_ROUTE_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_MOE_ROUTE_KERNEL_ID_STABLE_TOPK_V1: u32 = 1;
pub const SLLM_HIP_MOE_ROUTE_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_MOE_ROUTE_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_MOE_ROUTE_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_MOE_ROUTE_MAX_TOKENS: u64 = 65_536;
pub const SLLM_HIP_MOE_ROUTE_MAX_EXPERTS: u64 = 256;
pub const SLLM_HIP_MOE_ROUTE_MAX_SELECTED: u32 = 16;
pub const SLLM_HIP_MOE_EXPERT_VERSION: u32 = 1;
pub const SLLM_HIP_MOE_EXPERT_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_MOE_EXPERT_KERNEL_ID_DECODE_V1: u32 = 1;
pub const SLLM_HIP_MOE_EXPERT_KERNEL_ID_PREFILL_V1: u32 = 2;
pub const SLLM_HIP_MOE_EXPERT_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_MOE_EXPERT_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_MOE_EXPERT_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_MOE_EXPERT_HIDDEN_SIZE: u32 = 2048;
pub const SLLM_HIP_MOE_EXPERT_INTERMEDIATE_SIZE: u32 = 512;
pub const SLLM_HIP_MOE_EXPERT_COUNT: u32 = 256;
pub const SLLM_HIP_MOE_EXPERT_TOPK: u32 = 8;
pub const SLLM_HIP_MOE_EXPERT_LAYER_BLOB_BYTES: u64 = 434_114_560;
pub const SLLM_HIP_MOE_EXPERT_MAX_TOKENS: u64 = 65_536;
pub const SLLM_HIP_ATTENTION_PREPROCESS_VERSION: u32 = 1;
pub const SLLM_HIP_ATTENTION_PREPROCESS_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_ATTENTION_PREPROCESS_KERNEL_ID_BASELINE_BF16_V1: u32 = 1;
pub const SLLM_HIP_ATTENTION_PREPROCESS_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_ATTENTION_PREPROCESS_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_ATTENTION_PREPROCESS_WORKGROUP_SIZE: u32 = 1;
pub const SLLM_HIP_ATTENTION_PREPROCESS_Q_HEADS: u32 = 16;
pub const SLLM_HIP_ATTENTION_PREPROCESS_K_HEADS: u32 = 4;
pub const SLLM_HIP_ATTENTION_PREPROCESS_Q_HEAD_DIM: u32 = 256;
pub const SLLM_HIP_ATTENTION_PREPROCESS_K_HEAD_DIM: u32 = 256;
pub const SLLM_HIP_ATTENTION_PREPROCESS_QGATE_HEAD_DIM: u32 = 512;
pub const SLLM_HIP_ATTENTION_PREPROCESS_ROTARY_DIM: u32 = 64;
pub const SLLM_HIP_ATTENTION_PREPROCESS_MAX_POSITION: u32 = 262_144;
pub const SLLM_HIP_ATTENTION_PREPROCESS_MAX_M: u64 = 262_144;
pub const SLLM_HIP_ROTARY_VERSION: u32 = 1;
pub const SLLM_HIP_ROTARY_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_ROTARY_KERNEL_ID_SPLIT_HALF_BF16_FP32_V1: u32 = 1;
pub const SLLM_HIP_ROTARY_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_ROTARY_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_ROTARY_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_ROTARY_MAX_M: u64 = 262_144;
pub const SLLM_HIP_ROTARY_MAX_POSITION: u32 = 262_144;
pub const SLLM_HIP_WINDOWED_ATTENTION_VERSION: u32 = 1;
pub const SLLM_HIP_WINDOWED_ATTENTION_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_WINDOWED_ATTENTION_KERNEL_ID_ONLINE_SOFTMAX_GQA_BF16_V1: u32 = 1;
pub const SLLM_HIP_WINDOWED_ATTENTION_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_WINDOWED_ATTENTION_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_WINDOWED_ATTENTION_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_WINDOWED_ATTENTION_MAX_M: u64 = 262_144;
pub const SLLM_HIP_WINDOWED_ATTENTION_MAX_KV: u64 = 262_144;
pub const SLLM_HIP_WINDOWED_ATTENTION_MAX_HEAD_DIM: u32 = 512;
pub const SLLM_HIP_KV_STATE_VERSION: u32 = 2;
pub const SLLM_HIP_KV_STATE_CREATE_INFO_V2_VERSION: u32 = 1;
pub const SLLM_HIP_KV_STATE_CREATE_INFO_STATIC_FP8_VERSION: u32 = 2;
pub const SLLM_HIP_KV_VIEW_INFO_VERSION: u32 = 2;
pub const SLLM_HIP_KV_APPEND_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_KV_HEAD_COUNT: u32 = 4;
pub const SLLM_HIP_KV_HEAD_DIM: u32 = 256;
pub const SLLM_HIP_KV_MAX_HEAD_DIM: u32 = 512;
pub const SLLM_HIP_KV_MAX_CAPACITY: u64 = 262_144;
pub const SLLM_HIP_KV_MAX_M: u64 = 262_144;
pub const SLLM_HIP_KV_KERNEL_ID_BF16_TO_F16_TRANSPOSE_V1: u32 = 1;
pub const SLLM_HIP_KV_KERNEL_ID_BF16_TO_F16_TOKEN_MAJOR_V2: u32 = 2;
pub const SLLM_HIP_KV_KERNEL_ID_BF16_TO_FP8_TOKEN_MAJOR_V1: u32 = 3;
pub const SLLM_HIP_KV_KERNEL_ID_BF16_TO_NVFP4_TOKEN_MAJOR_V1: u32 = 4;
pub const SLLM_HIP_KV_KERNEL_ID_BF16_TO_FP8_STATIC_TOKEN_MAJOR_V1: u32 = 5;
pub const SLLM_HIP_KV_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_KV_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_KV_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_KV_MEMORY_KIND_VIRTUAL_CONTIGUOUS: u32 = 1;
pub const SLLM_HIP_KV_MEMORY_KIND_CAPABILITY_SELECTED: u32 = 0;
pub const SLLM_HIP_KV_MEMORY_KIND_CONTIGUOUS_RESIDENT: u32 = 2;
pub const SLLM_HIP_KV_LAYOUT_TOKEN_MAJOR: u32 = 1;
pub const SLLM_HIP_KV_ENCODING_FP16_V1: u32 = 0;
pub const SLLM_HIP_KV_ENCODING_FP8_V1: u32 = 1;
pub const SLLM_HIP_KV_ENCODING_NVFP4_V1: u32 = 2;
pub const SLLM_HIP_KV_ENCODING_FP8_STATIC_V1: u32 = 3;
pub const SLLM_HIP_CAUSAL_ATTENTION_VERSION: u32 = 1;
pub const SLLM_HIP_CAUSAL_ATTENTION_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_CAUSAL_ATTENTION_KERNEL_ID_STABLE_SOFTMAX_V1: u32 = 1;
pub const SLLM_HIP_CAUSAL_ATTENTION_KERNEL_ID_ONLINE_SOFTMAX_V2: u32 = 2;
pub const SLLM_HIP_CAUSAL_ATTENTION_KERNEL_ID_PACKED_KV_V3: u32 = 3;
pub const SLLM_HIP_CAUSAL_ATTENTION_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_CAUSAL_ATTENTION_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_CAUSAL_ATTENTION_WORKGROUP_SIZE: u32 = 256;
pub const SLLM_HIP_CAUSAL_ATTENTION_Q_HEADS: u32 = 16;
pub const SLLM_HIP_CAUSAL_ATTENTION_KV_HEADS: u32 = 4;
pub const SLLM_HIP_CAUSAL_ATTENTION_HEAD_DIM: u32 = 256;
pub const SLLM_HIP_CAUSAL_ATTENTION_SCALE_DENOMINATOR: u32 = 16;
pub const SLLM_HIP_CAUSAL_ATTENTION_MAX_M: u64 = 262_144;
pub const SLLM_HIP_LINEAR_ATTENTION_VERSION: u32 = 1;
pub const SLLM_HIP_LINEAR_ATTENTION_VIEW_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_LINEAR_ATTENTION_DISPATCH_INFO_VERSION: u32 = 1;
pub const SLLM_HIP_LINEAR_ATTENTION_KERNEL_ID_CAUSAL_CONV_SILU_V1: u32 = 1;
pub const SLLM_HIP_LINEAR_ATTENTION_KERNEL_ID_RECURRENT_GATED_NORM_V1: u32 = 2;
pub const SLLM_HIP_LINEAR_ATTENTION_KERNEL_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_LINEAR_ATTENTION_DEVICE_SYMBOL_MAX: u32 = 64;
pub const SLLM_HIP_LINEAR_ATTENTION_WORKGROUP_SIZE: u32 = 128;
pub const SLLM_HIP_LINEAR_ATTENTION_QK_HEADS: u32 = 16;
pub const SLLM_HIP_LINEAR_ATTENTION_VALUE_HEADS: u32 = 32;
pub const SLLM_HIP_LINEAR_ATTENTION_HEAD_DIM: u32 = 128;
pub const SLLM_HIP_LINEAR_ATTENTION_QKV_WIDTH: u32 = 8192;
pub const SLLM_HIP_LINEAR_ATTENTION_OUTPUT_WIDTH: u32 = 4096;
pub const SLLM_HIP_LINEAR_ATTENTION_CONV_KERNEL_SIZE: u32 = 4;
pub const SLLM_HIP_LINEAR_ATTENTION_CONV_HISTORY: u32 = 3;
pub const SLLM_HIP_LINEAR_ATTENTION_MAX_CAPACITY: u64 = 262_144;
pub const SLLM_HIP_LINEAR_ATTENTION_MAX_M: u64 = 262_144;

pub const SLLM_BACKEND_HIP: u32 = 1;

pub type sllm_access_mode_t = u32;

pub const SLLM_ACCESS_READ: sllm_access_mode_t = 1;
pub const SLLM_ACCESS_WRITE: sllm_access_mode_t = 2;
pub const SLLM_ACCESS_READ_WRITE: sllm_access_mode_t = 3;

pub const SLLM_HIP_MAX_DEVICE_NAME: u32 = 128;
pub const SLLM_HIP_MAX_GCN_ARCH_NAME: u32 = 64;
pub const SLLM_HIP_MAX_TRANSFER_BYTES: u64 = 1_073_741_824;
pub const SLLM_HIP_RMSNORM_VERSION: u32 = 1;
pub const SLLM_HIP_TENSOR_MAX_RANK: u32 = 8;

pub type sllm_tensor_dtype_t = u32;
pub const SLLM_TENSOR_DTYPE_BF16: sllm_tensor_dtype_t = 0;
pub const SLLM_TENSOR_DTYPE_F16: sllm_tensor_dtype_t = 1;
pub const SLLM_TENSOR_DTYPE_F32: sllm_tensor_dtype_t = 2;
pub const SLLM_TENSOR_DTYPE_F8_E4M3_FN: sllm_tensor_dtype_t = 3;
pub const SLLM_TENSOR_DTYPE_F8_E4M3_FNUZ: sllm_tensor_dtype_t = 4;
pub const SLLM_TENSOR_DTYPE_U8: sllm_tensor_dtype_t = 9;
pub const SLLM_TENSOR_DTYPE_I32: sllm_tensor_dtype_t = 8;
pub type sllm_tensor_encoding_t = u32;
pub const SLLM_TENSOR_ENCODING_UNQUANTIZED: sllm_tensor_encoding_t = 0;
pub const SLLM_TENSOR_ENCODING_FP8_OUTER_F32: sllm_tensor_encoding_t = 1;
pub const SLLM_TENSOR_ENCODING_NVFP4_BLOCK16_E4M3FN_F32: sllm_tensor_encoding_t = 2;
pub const SLLM_TENSOR_ENCODING_NVFP4_W4A4_BLOCK16_E4M3FN_F32: sllm_tensor_encoding_t = 3;
pub const SLLM_TENSOR_ENCODING_MXFP4_W4A4_BLOCK32_E8M0: sllm_tensor_encoding_t = 4;
pub type sllm_rmsnorm_accumulation_dtype_t = u32;
pub const SLLM_RMSNORM_ACCUMULATION_F32: sllm_rmsnorm_accumulation_dtype_t = 2;
pub type sllm_rmsnorm_scale_mode_t = u32;
pub const SLLM_RMSNORM_SCALE_MODE_OFFSET_ONE: sllm_rmsnorm_scale_mode_t = 1;
pub const SLLM_RMSNORM_SCALE_MODE_DIRECT: sllm_rmsnorm_scale_mode_t = 2;
pub type sllm_rmsnorm_alias_policy_t = u32;
pub const SLLM_RMSNORM_ALIAS_POLICY_REJECT_OVERLAP: sllm_rmsnorm_alias_policy_t = 1;
pub type sllm_elementwise_operation_t = u32;
pub const SLLM_ELEMENTWISE_OPERATION_COPY: sllm_elementwise_operation_t = 1;
pub const SLLM_ELEMENTWISE_OPERATION_ADD: sllm_elementwise_operation_t = 2;
pub const SLLM_ELEMENTWISE_OPERATION_SILU_MUL: sllm_elementwise_operation_t = 3;
pub const SLLM_ELEMENTWISE_OPERATION_SIGMOID_MUL: sllm_elementwise_operation_t = 4;
pub const SLLM_ELEMENTWISE_OPERATION_SCALAR_MUL: sllm_elementwise_operation_t = 5;
pub const SLLM_ELEMENTWISE_OPERATION_GELU_TANH_MUL: sllm_elementwise_operation_t = 6;
pub const SLLM_ELEMENTWISE_OPERATION_TANH_SOFTCAP: sllm_elementwise_operation_t = 7;

pub const SLLM_COMPLETION_STATE_PENDING: u32 = 0;
pub const SLLM_COMPLETION_STATE_SUCCESS: u32 = 1;
pub const SLLM_COMPLETION_STATE_FAILURE: u32 = 2;

#[repr(C)]
pub struct sllm_context_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_queue_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_buffer_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_event_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_completion_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_rmsnorm_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_elementwise_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_embedding_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_matmul_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_argmax_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_moe_route_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_moe_expert_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_attention_preprocess_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_rotary_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_windowed_attention_plan_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_kv_state_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_kv_view_t {
    _private: [u8; 0],
}

#[repr(C)]
pub struct sllm_linear_attention_state_t {
    _private: [u8; 0],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_error_sink_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub message: *mut c_char,
    pub message_capacity: u64,
    pub message_length: u64,
    pub reserved: [u64; 2],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_version_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub major: u32,
    pub minor: u32,
    pub patch: u32,
    pub reserved: [u32; 3],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_backend_probe_result_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub backend: u32,
    pub available: u32,
    pub hip_runtime_present: u32,
    pub reserved: [u32; 3],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_context_probe_result_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub context_present: u32,
    pub hip_available: u32,
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_device_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub device_index: u32,
    pub visible_device_count: u32,
    pub total_memory_bytes: u64,
    pub wavefront_size: u32,
    pub reserved0: u32,
    pub name: [c_char; 128],
    pub gcn_arch_name: [c_char; 64],
    pub available_memory_bytes: u64,
    pub reserved: [u32; 2],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_context_create_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub device_index: u32,
    pub flags: u32,
    pub expected_gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_queue_create_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub flags: u32,
    pub reserved: [u32; 5],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_buffer_create_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub size_bytes: u64,
    pub alignment_bytes: u64,
    pub flags: u32,
    pub reserved: [u32; 5],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_transfer_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub host_pointer: *mut core::ffi::c_void,
    pub buffer_offset_bytes: u64,
    pub size_bytes: u64,
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_completion_result_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub state: u32,
    pub reserved0: u32,
    pub transfer_size_bytes: u64,
    pub available_bytes: u64,
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_completion_timing_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub valid: u32,
    pub reserved0: u32,
    pub elapsed_ns: u64,
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_tensor_binding_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub buffer: *const sllm_buffer_t,
    pub byte_offset: u64,
    pub dtype: sllm_tensor_dtype_t,
    pub encoding: sllm_tensor_encoding_t,
    pub rank: u32,
    pub reserved0: u32,
    pub shape: [u64; 8],
    pub stride_elements: [u64; 8],
    pub reserved: [u64; 2],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_rmsnorm_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub accumulation_dtype: sllm_rmsnorm_accumulation_dtype_t,
    pub scale_mode: sllm_rmsnorm_scale_mode_t,
    pub alias_policy: sllm_rmsnorm_alias_policy_t,
    pub epsilon_bits: u32,
    pub reserved: [u32; 3],
    pub activation: sllm_tensor_binding_t,
    pub raw_scale: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_rmsnorm_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub row_count: u64,
    pub normalized_size: u64,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_elementwise_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub operation: sllm_elementwise_operation_t,
    pub reserved: [u32; 4],
    pub input0: sllm_tensor_binding_t,
    pub input1: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_elementwise_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub operation: sllm_elementwise_operation_t,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub element_count: u64,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_embedding_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub reserved: [u32; 5],
    pub weight: sllm_tensor_binding_t,
    pub token_ids: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_embedding_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub token_count: u64,
    pub hidden_size: u64,
    pub vocab_size: u64,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_matmul_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub reserved: [u32; 5],
    pub activation: sllm_tensor_binding_t,
    pub weight: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_matmul_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub m: u64,
    pub k: u64,
    pub n: u64,
    pub output_elements: u64,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_argmax_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub reserved: [u32; 5],
    pub logits: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_argmax_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub row_count: u64,
    pub vocab_size: u64,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_moe_route_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub selected_expert_count: u32,
    pub reserved: [u32; 4],
    pub logits: sllm_tensor_binding_t,
    pub metadata: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_moe_route_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub token_count: u64,
    pub expert_count: u64,
    pub pair_count: u64,
    pub selected_expert_count: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub reserved0: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_moe_expert_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub reserved0: u32,
    pub reserved: [u32; 4],
    pub hidden: sllm_tensor_binding_t,
    pub routing_metadata: sllm_tensor_binding_t,
    pub layer_blob: sllm_tensor_binding_t,
    pub workspace: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_moe_expert_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub token_count: u64,
    pub active_pair_count: u64,
    pub workspace_bytes: u64,
    pub selected_expert_count: u32,
    pub shared_expert_count: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_attention_preprocess_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub start_position: u32,
    pub reserved: [u32; 4],
    pub packed_q_gate: sllm_tensor_binding_t,
    pub k: sllm_tensor_binding_t,
    pub q_raw_scale: sllm_tensor_binding_t,
    pub k_raw_scale: sllm_tensor_binding_t,
    pub positions: sllm_tensor_binding_t,
    pub q_output: sllm_tensor_binding_t,
    pub gate_output: sllm_tensor_binding_t,
    pub k_output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_attention_preprocess_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub m: u64,
    pub q_heads: u32,
    pub k_heads: u32,
    pub q_head_dim: u32,
    pub k_head_dim: u32,
    pub rotary_dim: u32,
    pub start_position: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_rotary_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub reserved0: u32,
    pub start_position: u64,
    pub q_heads: u32,
    pub kv_heads: u32,
    pub head_dim: u32,
    pub rotary_dim: u32,
    pub theta_bits: u32,
    pub max_position: u32,
    pub reserved: [u32; 2],
    pub query: sllm_tensor_binding_t,
    pub key: sllm_tensor_binding_t,
    pub positions: sllm_tensor_binding_t,
    pub query_output: sllm_tensor_binding_t,
    pub key_output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_rotary_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub token_count: u64,
    pub q_heads: u32,
    pub kv_heads: u32,
    pub head_dim: u32,
    pub rotary_dim: u32,
    pub start_position: u32,
    pub max_position: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_windowed_attention_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub reserved0: u32,
    pub start_position: u64,
    pub expected_kv_length: u64,
    pub sliding_window: u64,
    pub q_heads: u32,
    pub kv_heads: u32,
    pub head_dim: u32,
    pub scaling_bits: u32,
    pub reserved: [u32; 4],
    pub query: sllm_tensor_binding_t,
    pub key: sllm_tensor_binding_t,
    pub value: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_windowed_attention_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub query_count: u64,
    pub start_position: u64,
    pub committed_kv_length: u64,
    pub sliding_window: u64,
    pub q_heads: u32,
    pub kv_heads: u32,
    pub head_dim: u32,
    pub scaling_bits: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_kv_state_create_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub session_id: u64,
    pub layer_id: u32,
    pub flags: u32,
    pub capacity_tokens: u64,
    pub head_count: u32,
    pub head_dim: u32,
    pub memory_kind: u32,
    pub layout: u32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_kv_state_create_info_v2_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub create_info_version: u32,
    pub reserved0: u32,
    pub session_id: u64,
    pub layer_id: u32,
    pub flags: u32,
    pub capacity_tokens: u64,
    pub head_count: u32,
    pub head_dim: u32,
    pub memory_kind: u32,
    pub layout: u32,
    pub dtype: u32,
    pub encoding: u32,
    pub block_size: u32,
    pub scale_dtype: u32,
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_kv_view_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub reserved0: u32,
    pub session_id: u64,
    pub layer_id: u32,
    pub dtype: u32,
    pub encoding: u32,
    pub head_count: u32,
    pub head_dim: u32,
    pub memory_kind: u32,
    pub layout: u32,
    pub reserved1: u32,
    pub capacity_tokens: u64,
    pub observed_length: u64,
    pub generation: u64,
    pub physical_page_bytes: u64,
    pub tokens_per_page: u64,
    pub mapped_token_capacity: u64,
    pub committed_bytes_per_plane: u64,
    pub context_identity: u64,
    pub state_identity: u64,
    pub k_stride_elements: [u64; 3],
    pub v_stride_elements: [u64; 3],
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_kv_append_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub append_version: u32,
    pub reserved0: u32,
    pub expected_length: u64,
    pub start_position: u64,
    pub key_input: sllm_tensor_binding_t,
    pub value_input: sllm_tensor_binding_t,
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_kv_append_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub start_position: u64,
    pub token_count: u64,
    pub end_position: u64,
    pub commit_allowed: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub reserved0: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_causal_attention_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub reserved0: u32,
    pub start_position: u64,
    pub expected_kv_length: u64,
    pub kv_state: *const sllm_kv_state_t,
    pub query: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_causal_attention_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub kernel_id: u32,
    pub workgroup_size_x: u32,
    pub grid_size_x: u32,
    pub query_count: u64,
    pub start_position: u64,
    pub committed_kv_length: u64,
    pub q_heads: u32,
    pub kv_heads: u32,
    pub head_dim: u32,
    pub scale_denominator: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub kernel_symbol: [c_char; 64],
    pub device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_linear_attention_state_create_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub session_id: u64,
    pub layer_id: u32,
    pub flags: u32,
    pub capacity_tokens: u64,
    pub qk_heads: u32,
    pub value_heads: u32,
    pub head_dim: u32,
    pub conv_kernel_size: u32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_linear_attention_view_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub reserved0: u32,
    pub session_id: u64,
    pub layer_id: u32,
    pub conv_state_dtype: u32,
    pub recurrent_state_dtype: u32,
    pub encoding: u32,
    pub active_slot: u32,
    pub capacity_tokens: u64,
    pub observed_length: u64,
    pub generation: u64,
    pub context_identity: u64,
    pub state_identity: u64,
    pub conv_state_shape: [u64; 2],
    pub recurrent_state_shape: [u64; 3],
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_linear_attention_desc_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub op_version: u32,
    pub reserved0: u32,
    pub start_position: u64,
    pub expected_length: u64,
    pub state: *const sllm_linear_attention_state_t,
    pub qkv: sllm_tensor_binding_t,
    pub z: sllm_tensor_binding_t,
    pub b_input: sllm_tensor_binding_t,
    pub a_input: sllm_tensor_binding_t,
    pub conv_weight: sllm_tensor_binding_t,
    pub a_log: sllm_tensor_binding_t,
    pub dt_bias: sllm_tensor_binding_t,
    pub norm_weight: sllm_tensor_binding_t,
    pub output: sllm_tensor_binding_t,
    pub reserved: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct sllm_linear_attention_dispatch_info_t {
    pub struct_size: u32,
    pub abi_version: u32,
    pub info_version: u32,
    pub backend: u32,
    pub dispatch_id: u64,
    pub dispatch_count: u32,
    pub conv_kernel_id: u32,
    pub recurrent_kernel_id: u32,
    pub workgroup_size_x: u32,
    pub conv_grid_size_x: u32,
    pub recurrent_grid_size_x: u32,
    pub token_count: u64,
    pub start_position: u64,
    pub expected_length: u64,
    pub qk_heads: u32,
    pub value_heads: u32,
    pub head_dim: u32,
    pub fallback_allowed: u32,
    pub fallback_used: u32,
    pub kernel_symbol: [c_char; 64],
    pub conv_device_symbol: [c_char; 64],
    pub recurrent_device_symbol: [c_char; 64],
    pub gcn_arch_name: [c_char; 64],
    pub reserved: [u32; 8],
}

unsafe extern "C" {
    pub fn sllm_get_abi_version(
        abi_version: *mut u32,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_query_version(
        version: *mut sllm_version_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_backend_probe(
        backend: u32,
        result: *mut sllm_backend_probe_result_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_context_probe(
        context: *const sllm_context_t,
        result: *mut sllm_context_probe_result_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_device_count(count: *mut u32, error_sink: *mut sllm_error_sink_t) -> sllm_status_t;
    pub fn sllm_device_query(
        device_index: u32,
        info: *mut sllm_device_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_context_create(
        info: *const sllm_context_create_info_t,
        context: *mut *mut sllm_context_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_context_release(
        context: *mut *mut sllm_context_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_queue_create(
        context: *const sllm_context_t,
        info: *const sllm_queue_create_info_t,
        queue: *mut *mut sllm_queue_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_queue_release(
        queue: *mut *mut sllm_queue_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_buffer_create(
        context: *const sllm_context_t,
        info: *const sllm_buffer_create_info_t,
        buffer: *mut *mut sllm_buffer_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_buffer_release(
        buffer: *mut *mut sllm_buffer_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_buffer_size(
        buffer: *const sllm_buffer_t,
        size_bytes: *mut u64,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_event_create(
        context: *const sllm_context_t,
        event: *mut *mut sllm_event_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_event_release(
        event: *mut *mut sllm_event_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_buffer_copy_h2d(
        queue: *const sllm_queue_t,
        buffer: *const sllm_buffer_t,
        transfer: *const sllm_transfer_desc_t,
        completion: *mut *mut sllm_completion_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_buffer_copy_d2h(
        queue: *const sllm_queue_t,
        buffer: *const sllm_buffer_t,
        transfer: *const sllm_transfer_desc_t,
        completion: *mut *mut sllm_completion_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_completion_query(
        completion: *mut sllm_completion_t,
        result: *mut sllm_completion_result_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_completion_wait(
        completion: *mut sllm_completion_t,
        timeout_ms: u32,
        result: *mut sllm_completion_result_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_completion_read(
        completion: *mut sllm_completion_t,
        destination: *mut core::ffi::c_void,
        destination_capacity: u64,
        bytes_written: *mut u64,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_completion_timing(
        completion: *mut sllm_completion_t,
        timing: *mut sllm_completion_timing_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_completion_release(
        completion: *mut *mut sllm_completion_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_rmsnorm_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_rmsnorm_desc_t,
        plan: *mut *mut sllm_rmsnorm_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_rmsnorm_plan_release(
        plan: *mut *mut sllm_rmsnorm_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_rmsnorm_execute(
        plan: *const sllm_rmsnorm_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_rmsnorm_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_elementwise_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_elementwise_desc_t,
        plan: *mut *mut sllm_elementwise_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_elementwise_plan_release(
        plan: *mut *mut sllm_elementwise_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_elementwise_execute(
        plan: *const sllm_elementwise_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_elementwise_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_embedding_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_embedding_desc_t,
        plan: *mut *mut sllm_embedding_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_embedding_plan_release(
        plan: *mut *mut sllm_embedding_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_embedding_execute(
        plan: *const sllm_embedding_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_embedding_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_matmul_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_matmul_desc_t,
        plan: *mut *mut sllm_matmul_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_matmul_plan_release(
        plan: *mut *mut sllm_matmul_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_matmul_execute(
        plan: *const sllm_matmul_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_matmul_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_argmax_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_argmax_desc_t,
        plan: *mut *mut sllm_argmax_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_argmax_plan_release(
        plan: *mut *mut sllm_argmax_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_argmax_execute(
        plan: *const sllm_argmax_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_argmax_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_moe_route_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_moe_route_desc_t,
        plan: *mut *mut sllm_moe_route_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_moe_route_plan_release(
        plan: *mut *mut sllm_moe_route_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_moe_route_execute(
        plan: *const sllm_moe_route_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_moe_route_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_moe_expert_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_moe_expert_desc_t,
        plan: *mut *mut sllm_moe_expert_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_moe_expert_plan_release(
        plan: *mut *mut sllm_moe_expert_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_moe_expert_execute(
        plan: *const sllm_moe_expert_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_moe_expert_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_attention_preprocess_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_attention_preprocess_desc_t,
        plan: *mut *mut sllm_attention_preprocess_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_attention_preprocess_plan_release(
        plan: *mut *mut sllm_attention_preprocess_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_attention_preprocess_execute(
        plan: *const sllm_attention_preprocess_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_attention_preprocess_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_rotary_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_rotary_desc_t,
        plan: *mut *mut sllm_rotary_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_rotary_plan_release(
        plan: *mut *mut sllm_rotary_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_rotary_execute(
        plan: *const sllm_rotary_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_rotary_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_windowed_attention_prepare(
        context: *const sllm_context_t,
        descriptor: *const sllm_windowed_attention_desc_t,
        plan: *mut *mut sllm_windowed_attention_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_windowed_attention_plan_release(
        plan: *mut *mut sllm_windowed_attention_plan_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_windowed_attention_execute(
        plan: *const sllm_windowed_attention_plan_t,
        queue: *const sllm_queue_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_windowed_attention_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_state_create(
        context: *const sllm_context_t,
        info: *const sllm_kv_state_create_info_t,
        state: *mut *mut sllm_kv_state_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_state_create_v2(
        context: *const sllm_context_t,
        info: *const sllm_kv_state_create_info_v2_t,
        state: *mut *mut sllm_kv_state_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_state_release(
        state: *mut *mut sllm_kv_state_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_state_query(
        state: *const sllm_kv_state_t,
        info: *mut sllm_kv_view_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_state_rewind_last(
        state: *const sllm_kv_state_t,
        expected_length: u64,
        rewind_length: u64,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_state_snapshot(
        state: *const sllm_kv_state_t,
        view: *mut *mut sllm_kv_view_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_view_query(
        view: *const sllm_kv_view_t,
        info: *mut sllm_kv_view_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_view_release(
        view: *mut *mut sllm_kv_view_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_state_append(
        state: *const sllm_kv_state_t,
        queue: *const sllm_queue_t,
        descriptor: *const sllm_kv_append_desc_t,
        completion: *mut *mut sllm_completion_t,
        append_info: *mut sllm_kv_append_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_kv_state_append_cancel(
        state: *const sllm_kv_state_t,
        completion: *mut sllm_completion_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_causal_attention_execute(
        context: *const sllm_context_t,
        queue: *const sllm_queue_t,
        descriptor: *const sllm_causal_attention_desc_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_causal_attention_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_linear_attention_state_create(
        context: *const sllm_context_t,
        info: *const sllm_linear_attention_state_create_info_t,
        state: *mut *mut sllm_linear_attention_state_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_linear_attention_state_release(
        state: *mut *mut sllm_linear_attention_state_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_linear_attention_state_query(
        state: *const sllm_linear_attention_state_t,
        info: *mut sllm_linear_attention_view_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_linear_attention_state_rewind_last(
        state: *const sllm_linear_attention_state_t,
        expected_length: u64,
        rewind_length: u64,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_linear_attention_execute(
        context: *const sllm_context_t,
        queue: *const sllm_queue_t,
        descriptor: *const sllm_linear_attention_desc_t,
        completion: *mut *mut sllm_completion_t,
        dispatch_info: *mut sllm_linear_attention_dispatch_info_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
    pub fn sllm_linear_attention_cancel(
        state: *const sllm_linear_attention_state_t,
        completion: *mut sllm_completion_t,
        error_sink: *mut sllm_error_sink_t,
    ) -> sllm_status_t;
}
